package.json, src/components/PBSCPhoneNumberField.js, src/helpers/DateTimeService.js
1. Resolved locale id issue
2. Changed text color when `hasError` is `true` for `PhoneNumberField`
=> Fixed locale id issue on DateTimeService

package.json, src/components/PBSCPhoneNumberField.js
Resolved issue of color on `PhoneNumberField` when it has error and disable.
Please refer the screenshot below.
.
=> Resolved issue on PhoneNumberField when disabled and has error

package.json, src/components/PBSCTextField.js
- [Support] - Able to add custom right side icon in text input
- [Bug] - Fixed library issue
=> Improvements - Custom Icon support in textInput & Bug fixes

.github/workflows/lint-tests.yml, .github/workflows/push-to-master.yml
- add names to the github workflow job
=> chore: add names to the github workflow job

CONTRIBUTING.md
edit CONTRIBUTING file to mention the commit message format
=> docs: edit CONTRIBUTING file

CONTRIBUTING.md
BREAKING CHANGE: edit the CONTRIBUTING.md doc
=> feat: edit documentation

CONTRIBUTING.md, package.json
edit the doc file to test the breaking change flow
BREAKING CHANGE: not a breaking change, just a test to see if the major version will get updated
=> docs(contributing): edit the doc file to test the breaking change flow

package.json
readd the parserOpts to see if breaking change will work
BREAKING CHANGE: test if the major version will get incremented
=> fix(package.json): add back the parserOpts for semantic-release

CONTRIBUTING.md, package.json
edit documentation to specify the commit message convention
BREAKING CHANGE: made this change to see if the major version will get incremented
=> docs: edit documentation

CONTRIBUTING.md
BREAKING CHANGE: test breaking change
BREAKING CHANGE: this is a test
=> docs: edit doc

CONTRIBUTING.md
test major version upgrade
BREAKING CHANGE: just a test
=> docs!: edit doc

package.json
- Override the semantic-release branch to main branch
=> :green_heart: ci: overrride the semantic-release branch to main

.husky/prepare-commit-msg, CONTRIBUTING.md
- Add commit hook that validates that a breaking change commit has an '!' in the commit subject
=> 🚚 chore: add new commit hook

.husky/prepare-commit-msg
https://jira.lyft.net/browse/MGW-515
- Exclude the chore(release) commit from the prepare-commit hook so that semantic-release would work on the main branch
=> :truck: fix: fix the prepare-commit hook

README.md
=> :memo: docs: edit REAMDE file

.husky/commit-msg, .husky/pre-commit, .husky/prepare-commit-msg, README.md
=> :memo: docs: add more details to the doc related to the CI/CD process

CICDProcess.md, README.md
set the commit as feature because I want to test if the patch version will be incremented
none.
Had to open this pr and make a change to see if semantic-release will increment the patch version or not. 
In the last commit that was added, the version remained the same.
=> :sparkles: feat: edit documentation

package.json
- edited the release rules of @semantic-release/commit-analyzer to mention the emoji for a feat change to see if the lib version will be incremented
- this is NOT an actual feature. I set it up as 'feat' just to test
=> :sparkles: feat: edit release rules for semantic-release

release.config.js
- trying to fix the semantic release so that it parses commit messages that contain an emoji
=> :sparkles: feat: edit header pattern for semantic release

release.config.js
related to https://jira.lyft.net/browse/MGW-451
still trying to figure out what why semantic release is not parsing well the commit msg
=> feat: comment headerPattern

commitlint.config.js, release.config.js
=> :sparkles: feat: revert to gitmoji

release.config.js
=> :sparkles: feat: add header correspondence

release.config.js
=> :sparkles: feat(custom): edit header correspondence

release.config.js
(put the JIRA ticket or issue here)
(briefly explain what does this PR do)
=> 🐛 fix: fix semantic release for emojis

release.config.js
- try conventionalcommits as preset instead of angular to see if we get more details in release notes
=> ci: edit semantic release preset to conventionalcommits

CICDProcess.md
=> docs: edit documentation of CD process

package.json, yarn.lock
=> feat: edit semantic-release config

CICDProcess.md, CONTRIBUTING.md, package.json
- switch to conventionalcommits preset to get better release note reports
=> ci: edit the semantic-release preset

CONTRIBUTING.md, package.json
=> docs(contributing.md): edit documentation

release.config.js
- Moved the semantic release config file out of package.json
=> ci: move semantic-release configs into a config file

.github/workflows/push-to-main.yml, CICDProcess.md
- explain in more details the CI/CD process
- put this change as BREAKING CHANGE to see if the major version will be upgraded.
=> docs!: edit documentation

CICDProcess.md
- test to see if major version will be updated
=> docs!: edit documenetation

.husky/prepare-commit-msg
test to see if major version will be updated
=> feat: edit precommit hook

.husky/prepare-commit-msg, release.config.js
still trying to figure out why major version is not updating despite having a BREAKING CHANGE in the commit footer
- remove parserOpts to see if breaking change commit will increment the major version
=> ci!: edit semantic release config

.husky/prepare-commit-msg
- edit prepare commit hook to add more validation for a major commit type
=> chore: edit precommit hook

release.config.js
MGW-451
- add back semantic-release/git to have updated versions in package.json when a new release is created
=> ci(release.config.js): add semantic-release/git

release.config.js
MGW-451
- reoder semantic-release plugins
=> ci(release.config.js): reorder semantic-release plugins

docs/checkbox.md, example/src/screens/HomeScreen.js, src/components/PBSCCheckbox.js
- MGW-620
- Edit the checkbox to make it receive a custom label component to be rendered as a label
- Edit the checkbox label to add an onPress event listener
=> feat: edit checkbox to provide a custom label component and to add an onPress event to the label

package.json, yarn.lock
[MGW-437](https://jira.lyft.net/browse/MGW-437)
- Fix(deps): Upgrade react-native-vector-icons
=> fix: library bugs - Upgrade react-native-vector-icons

package.json, yarn.lock
(put the JIRA ticket or issue here)
[MGW-1081](https://jira.lyft.net/browse/MGW-1081)
(briefly explain what does this PR do)
=> feat: update lib to be compatible with RN 0.77
